// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type RealEstatePricesDocumentDataSlicesSlice =
  | FaqSlice
  | NeighborhoodsListSlice
  | VariationBlockSlice
  | PriceBlockSlice
  | TitleSectionSlice;

/**
 * Content for real estate prices documents
 */
interface RealEstatePricesDocumentData {
  /**
   * Slice Zone field in *real estate prices*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: real_estate_prices.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<RealEstatePricesDocumentDataSlicesSlice> /**
   * Meta Title field in *real estate prices*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: real_estate_prices.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *real estate prices*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: real_estate_prices.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *real estate prices*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: real_estate_prices.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * real estate prices document from Prismic
 *
 * - **API ID**: `real_estate_prices`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RealEstatePricesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<RealEstatePricesDocumentData>,
    "real_estate_prices",
    Lang
  >;

export type AllDocumentTypes = RealEstatePricesDocument;

/**
 * Item in *Faq → Default → Primary → FAQS*
 */
export interface FaqSliceDefaultPrimaryFaqsItem {
  /**
   * Question field in *Faq → Default → Primary → FAQS*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.faqs[].question
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  question: prismic.KeyTextField;

  /**
   * Answer field in *Faq → Default → Primary → FAQS*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.faqs[].answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

/**
 * Primary content in *Faq → Default → Primary*
 */
export interface FaqSliceDefaultPrimary {
  /**
   * FAQS field in *Faq → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.faqs[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  faqs: prismic.GroupField<Simplify<FaqSliceDefaultPrimaryFaqsItem>>;
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Faq*
 */
type FaqSliceVariation = FaqSliceDefault;

/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: Faq
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSlice = prismic.SharedSlice<"faq", FaqSliceVariation>;

/**
 * Item in *NeighborhoodsList → Default → Primary → Nom du quartier*
 */
export interface NeighborhoodsListSliceDefaultPrimaryNameItem {
  /**
   * Title field in *NeighborhoodsList → Default → Primary → Nom du quartier*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: neighborhoods_list.default.primary.name[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *NeighborhoodsList → Default → Primary*
 */
export interface NeighborhoodsListSliceDefaultPrimary {
  /**
   * Nom du quartier field in *NeighborhoodsList → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: neighborhoods_list.default.primary.name[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  name: prismic.GroupField<
    Simplify<NeighborhoodsListSliceDefaultPrimaryNameItem>
  >;
}

/**
 * Default variation for NeighborhoodsList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NeighborhoodsListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NeighborhoodsListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NeighborhoodsList*
 */
type NeighborhoodsListSliceVariation = NeighborhoodsListSliceDefault;

/**
 * NeighborhoodsList Shared Slice
 *
 * - **API ID**: `neighborhoods_list`
 * - **Description**: NeighborhoodsList
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NeighborhoodsListSlice = prismic.SharedSlice<
  "neighborhoods_list",
  NeighborhoodsListSliceVariation
>;

/**
 * Primary content in *PriceBlock → Default → Primary*
 */
export interface PriceBlockSliceDefaultPrimary {
  /**
   * Prix moyen m² Appart field in *PriceBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: price_block.default.primary.apartment_price
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  apartment_price: prismic.RichTextField;

  /**
   * Prix moyen m² Maison field in *PriceBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: price_block.default.primary.house_price
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  house_price: prismic.RichTextField;
}

/**
 * Default variation for PriceBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PriceBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PriceBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PriceBlock*
 */
type PriceBlockSliceVariation = PriceBlockSliceDefault;

/**
 * PriceBlock Shared Slice
 *
 * - **API ID**: `price_block`
 * - **Description**: PriceBlock
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PriceBlockSlice = prismic.SharedSlice<
  "price_block",
  PriceBlockSliceVariation
>;

/**
 * Primary content in *TitleSection → Default → Primary*
 */
export interface TitleSectionSliceDefaultPrimary {
  /**
   * Title field in *TitleSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *TitleSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for TitleSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TitleSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TitleSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TitleSection*
 */
type TitleSectionSliceVariation = TitleSectionSliceDefault;

/**
 * TitleSection Shared Slice
 *
 * - **API ID**: `title_section`
 * - **Description**: TitleSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TitleSectionSlice = prismic.SharedSlice<
  "title_section",
  TitleSectionSliceVariation
>;

/**
 * Primary content in *VariationBlock → Default → Primary*
 */
export interface VariationBlockSliceDefaultPrimary {
  /**
   * Variation sur 12 mois (%) field in *VariationBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: variation_block.default.primary.price_variation
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  price_variation: prismic.RichTextField;
}

/**
 * Default variation for VariationBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VariationBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VariationBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VariationBlock*
 */
type VariationBlockSliceVariation = VariationBlockSliceDefault;

/**
 * VariationBlock Shared Slice
 *
 * - **API ID**: `variation_block`
 * - **Description**: VariationBlock
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VariationBlockSlice = prismic.SharedSlice<
  "variation_block",
  VariationBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      RealEstatePricesDocument,
      RealEstatePricesDocumentData,
      RealEstatePricesDocumentDataSlicesSlice,
      AllDocumentTypes,
      FaqSlice,
      FaqSliceDefaultPrimaryFaqsItem,
      FaqSliceDefaultPrimary,
      FaqSliceVariation,
      FaqSliceDefault,
      NeighborhoodsListSlice,
      NeighborhoodsListSliceDefaultPrimaryNameItem,
      NeighborhoodsListSliceDefaultPrimary,
      NeighborhoodsListSliceVariation,
      NeighborhoodsListSliceDefault,
      PriceBlockSlice,
      PriceBlockSliceDefaultPrimary,
      PriceBlockSliceVariation,
      PriceBlockSliceDefault,
      TitleSectionSlice,
      TitleSectionSliceDefaultPrimary,
      TitleSectionSliceVariation,
      TitleSectionSliceDefault,
      VariationBlockSlice,
      VariationBlockSliceDefaultPrimary,
      VariationBlockSliceVariation,
      VariationBlockSliceDefault,
    };
  }
}
