// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  back_to_top: dynamic(() => import("./BackToTop")),
  cta_block: dynamic(() => import("./CtaBlock")),
  faq: dynamic(() => import("./Faq")),
  neighborhoods_list: dynamic(() => import("./NeighborhoodsList")),
  price_block: dynamic(() => import("./PriceBlock")),
  title_section: dynamic(() => import("./TitleSection")),
  variation_block: dynamic(() => import("./VariationBlock")),
};
